### ISSUE TITLE
Extrinsics between the three cameras

### ISSUE THREAD

**Issue by hitdshu** [mit-aera/Blackbird-Dataset#22]
Hi, I could not find any information on the extrinsic transforms between the three cameras. Am I missing something? Can I find this information somewhere? 

Best,
Deshun

**Comment by varunmurali1** [comment]
You should be able to query all of the information from TF. This is the render configuration from FlightGoggles (https://github.com/mit-aera/FlightGoggles/blob/feature/IJRR_dataset/flightgoggles/config/sensors/blackbirdDatasetSensors.xml) which might be helpful.

**Comment by hitdshu** [comment]
> You should be able to query all of the information from TF. This is the render configuration from FlightGoggles (https://github.com/mit-aera/FlightGoggles/blob/feature/IJRR_dataset/flightgoggles/config/sensors/blackbirdDatasetSensors.xml) which might be helpful.

Thanks very much for your timely and kind reply. 

I'm not very familiar with ROS. The "TF" you said, means I can get the extrinsics from the rosbag for each dataset? 

I checked your link. But what is the meaning of the parameters there? Are they translation and the euler angle? The transform is expressed as tf_cam_body?

Best,
Deshun

**Comment by hitdshu** [comment]
Besides, what does the ground truth pose mean? Is it the SE3 trajectory of the body frame, i.e., the center of the stereo cameras?

**Comment by hitdshu** [comment]
I've inspected the rosbag. The rosbag contains the camera intrinsics. But the camera extrinsics are still not available there.

**Comment by varunmurali1** [comment]
Yes the ground truth pose is the trajectory of the body frame which is the center of the stereo cameras. In this [file](https://github.com/mit-aera/FlightGoggles/blob/feature/IJRR_dataset/flightgoggles/config/sensors/blackbirdDatasetSensors.xml) the parameters are published as translations and euler angles. You are also correct that it is the transform from body to camera.

**Comment by hitdshu** [comment]
> Yes the ground truth pose is the trajectory of the body frame which is the center of the stereo cameras. In this [file](https://github.com/mit-aera/FlightGoggles/blob/feature/IJRR_dataset/flightgoggles/config/sensors/blackbirdDatasetSensors.xml) the parameters are published as translations and euler angles. You are also correct that it is the transform from body to camera.

Your timely reply is very appreciated. Have a nice day.

Deshun
